### ISSUE TITLE
Which model performed best?

### ISSUE THREAD

**Issue by Risho92** [jishnujayakumar/MLRC2020-EmbedKGQA#2]
Nice work @jishnujayakumar . I was going to use SBert on EmbedKGQA. But you already did it, plus you did more models like Longformers. Can you also publish, what the result was for each of the combination you tested? I was going to use SBert + ComplEx. If your research found a different combination better, may be I will go with that.

**Comment by jishnujayakumar** [comment]
@Risho92, kindly look at the [reproducibility summary report](https://rescience.github.io/bibliography/P_2021.html). It has some typos. Please Ignore them. Also I would request you to use the discussion section to ask questions so that other people can get maximum help.
