### ISSUE TITLE
RoBERTa instead of LSTM and SBert instead of RoBERTa

### ISSUE THREAD

**Issue by dinani65** [jishnujayakumar/MLRC2020-EmbedKGQA#8]
According to the main paper, we have two options for question embedding: LSTM ans RoBERTa.
right?
and here u shows that using SBert works better than the previous ones.
am I missing some information?

**Comment by jishnujayakumar** [comment]
@dinani65, this repo holds the reproduced experiments along with some additional ones w.r.t. the MLRC2020 challenge. In the main paper, the authors have tried using LSTM and RoBERTa while here we have conducted experiments with various transformer models like RoBERTa, ALBERT, Longformer, SBERT, etc., and based on our experiments SBERT performed slightly better than RoBERTa. I hope this clarifies your doubt.
